### ISSUE TITLE
Graph Image API

### ISSUE THREAD

**Issue by franzvezuli** [keepacom/api_backend#15]
Hello, is there an equivalent method to request a graph image for an ASIN? Similar to this: https://keepa.com/#!discuss/t/graph-image-api/7928

I couldn't find it in the existing classes.

**Comment by saschaarthur** [comment]
hello,

no thats not included. Aldo it wouldnt make much sense, because your Images wont refresh compared to linking them directly whereever you need them.

Anyways if you still want to download them you could use something like https://www.php.net/manual/en/function.file-get-contents.php to fetch the content (binary) into an variable and
https://www.php.net/manual/en/function.file-put-contents.php to write the content into to a file.
